---
title: Maintain or Co-Maintain an rOpenSci Package!
author:
  - Maëlle Salmon
date: '2022-10-28'
slug: maintain-or-co-maintain-an-ropensci-package
categories: []
tags:
  - community
description: A list of packages who need your help, and a list of reasons why to help.
---

rOpenSci [suite of packages](/packages) is mainly composed of packages contributed by the community through [peer-review](/software-peer-review), and of packages maintained by staff. 
Over time, the commitments and availability of the original developers of a package change, which leads to some maintainers' stepping down from their maintainer role, or some maintainers' hoping for more teamwork and therefore looking for co-maintainers.
In this blog post we will explain why **you** might want to help, and we'll list the packages currently up for adoption or collaboration.

## Why maintain or co-maintain a package?

Maintaining or co-maintaining a package can have some advantages, on top of the big motivator "keep a cool package alive".
Maintenance work allow you to gain and practice software development skills (writing R functions, using GitHub interface, unit testing, technical writing in the documentation...).
Furthermore, it will give these skills of yours a public record.

Being an author of an _rOpenSci_ package means you have access to rOpenSci infrastructure (pkgdown docs building for all packages) and community (through our forum, our semi-open slack).
We're grateful for all contributions that help us provide a healthy suite of packages!

Co-maintaining might allow for more team work and more work division, and if that appeals to you, even as a the sole maintainer of a package, you could look for co-maintainers. :wink:

## What does it take to maintain or co-maintain a package?

How much time, what skills in particular?
Sadly the answers is "it depends". :wink:
In the list of packages in this post, some require a large overhaul (for instance essurvey whose data source underwent many changes) while others are more stable (for instance [robotstxt](https://github.com/ropensci/robotstxt/)).
Other criteria that might increase the workload are: popularity (many users' requests), code health (maybe a dependency could or should be swapped for a more modern or better maintained one), whether the package is on CRAN or you'd want it to be, etc.
Have a [look at the repository](/blog/2022/07/01/evaluating-github-activity-for-contributors/) to assess its needs and its toolset before volunteering, and don't hesitate to ask questions (in the volunteering issue, in a new issue if there is no volunteering issue).

## How long would you maintain or co-maintain a package?

Until you no longer want to. :wink:
Ideally, it'd be great for you to be reasonably confident you can spend some of your time on the package for at least one year.
As a maintainer, if you want to step down, please reach out to `info@ropensci.org` -- no need to wait for the next annual survey and suffer in silence.

## How to choose a package to (co-)maintain?

Although general technical skills will make you a good contributor to many packages, it is **crucial** to have specific interest in what a package does or the toolset it uses.
You might have that interest because you use that package at work or because its scope falls under your topics of interest, for instance.
Being very interested in a package will make you more motivated, furthermore the user community will likely be a community of your peers.

Last but not least, if you use the package you maintain at work, you might be able to tackle maintenance during your normal working hours which might be more sustainable than carving time for it on the side.

## Packages looking for maintainers!