StylesPath = .vale-styles
MinAlertLevel = suggestion
Packages = proselint, write-good, alex, Joblint
Vocab = Blog

[formats]
Rmd = md
qmd = md
rmd = md

[*.{md,qmd,rmd,Rmd}]
BasedOnStyles = Vale, proselint, write-good, alex, Joblint

# Ignore shortcodes
BlockIgnores = ({{<[^>]*>}})


# Turn off certain rules
Vale.Spelling = NO
alex.ProfanityUnlikely = NO
write-good.E-Prime = NO
write-good.TooWordy = NO
proselint.Typography = NO
proselint.Very = NO