StylesPath = .vale-styles
MinAlertLevel = suggestion
Packages = proselint, write-good, alex, Joblint
Vocab = Blog

[formats]
Rmd = md
qmd = md
rmd = md

[*.{md,qmd,rmd,Rmd}]
BasedOnStyles = Vale, proselint, write-good, alex, Joblint

# Ignore shortcodes
BlockIgnores = ({{<[^>]*>}})


# Turn off certain rules
Vale.Spelling = NO           # Use CSpell for spelling to have better control
alex.ProfanityUnlikely = NO  # Too many false positives where unlikely
write-good.E-Prime = NO    # Enforces a very formal style (i.e. doesn't like the "to be" verb)
write-good.TooWordy = NO    # Overkill suppression of adjectives and expressions considering this is a blog
proselint.Typography = NO   # Overkill for contributors: Wants symbols instead of characters (i.e. ... should be replaced with symbol of ellipses)
proselint.Very = NO          # Authors are allowed to use the work 'very' :D

# Lists of package rules
# https://github.com/vale-cli/alex/
# https://github.com/vale-cli/write-good/
# https://github.com/vale-cli/proselint

